/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Output.java
 *
 * Created on Jun 11, 2011, 8:48:10 AM
 */

package com.sale.ui.customer;

import com.sale.entity.Customer;
import java.util.ArrayList;

/**
 *
 * @author Chanhchua
 */
public class Output extends javax.swing.JPanel {
    private java.util.List<com.sale.entity.Customer> customerBufferList;
    /** Creates new form Output */
    public Output() {
        initComponents1();
        customerBufferList = new ArrayList<Customer>(customerList);
    }

    protected void initComponents1() {
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        SalePUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("SalePU").createEntityManager();
        customerQuery = java.beans.Beans.isDesignTime() ? null : SalePUEntityManager.createQuery("SELECT c FROM Customer c");
        customerList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : customerQuery.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerListTable = new javax.swing.JTable();
        showAllBtn = new javax.swing.JButton();
        showSelectedBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        arrangeBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();
        importBtn = new javax.swing.JButton();
        exportBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, customerList, customerListTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(customerListTable);
        customerListTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        showAllBtn.setText("Show All");
        showAllBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAllBtnMouseClicked(evt);
            }
        });

        showSelectedBtn.setText("Show selected");
        showSelectedBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showSelectedBtnMouseClicked(evt);
            }
        });

        searchBtn.setText("Search");

        arrangeBtn.setText("Arrange");

        printBtn.setText("Print");

        importBtn.setText("Import");

        exportBtn.setText("Export");

        deleteBtn.setText("Delete");

        addBtn.setText("Add");

        cancelBtn.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(showAllBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showSelectedBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arrangeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(importBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(exportBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAllBtn)
                    .addComponent(showSelectedBtn)
                    .addComponent(searchBtn)
                    .addComponent(arrangeBtn)
                    .addComponent(printBtn)
                    .addComponent(importBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportBtn)
                    .addComponent(deleteBtn)
                    .addComponent(addBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void showSelectedBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showSelectedBtnMouseClicked
        // TODO add your handling code here:
        System.out.println(customerListTable.getSelectedRowCount());
        customerList.clear();
    }//GEN-LAST:event_showSelectedBtnMouseClicked

    private void showAllBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAllBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_showAllBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager SalePUEntityManager;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton arrangeBtn;
    private javax.swing.JButton cancelBtn;
    private java.util.List<com.sale.entity.Customer> customerList;
    private javax.swing.JTable customerListTable;
    private javax.persistence.Query customerQuery;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton exportBtn;
    private javax.swing.JButton importBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton showAllBtn;
    private javax.swing.JButton showSelectedBtn;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
