/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Input.java
 *
 * Created on Jun 11, 2011, 8:00:14 AM
 */

package com.sale.ui.customer;

import com.sale.bean.form.CustomerForm;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author Chanhchua
 */
public class Input extends javax.swing.JPanel {
    EntityManagerFactory emf;
    EntityManager em;
    /** Creates new form Input */
    public Input() {
        initComponents();
        emf = Persistence.createEntityManagerFactory("SalePU");
        em = emf.createEntityManager();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        customerForm = new com.sale.bean.form.CustomerForm();
        customer = new com.sale.entity.Customer();
        jLabel1 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 30, 49, 23));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, customerForm, org.jdesktop.beansbinding.ELProperty.create("${id}"), idField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 31, 85, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 59, -1, -1));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, customerForm, org.jdesktop.beansbinding.ELProperty.create("${name}"), nameField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 162, -1));

        okBtn.setText("OK");
        okBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okBtnMouseClicked(evt);
            }
        });
        add(okBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 118, 56, -1));

        cancelBtn.setText("Cancel");
        add(cancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 118, -1, -1));

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnMouseClicked
        // TODO add your handling code here:
        em.getTransaction().begin();
        customer.setName(customerForm.getName());
        em.persist(customer);
        em.getTransaction().commit();
        
    }//GEN-LAST:event_okBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private com.sale.entity.Customer customer;
    private com.sale.bean.form.CustomerForm customerForm;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton okBtn;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
